services:

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ElectroStore
      MYSQL_USER: user
      MYSQL_PASSWORD: 123123
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uuser -p123123"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - mysqldata:/var/lib/mysql
      - ./electro/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./electro/src/main/resources/db/sampledata.sql:/docker-entrypoint-initdb.d/sampledata.sql:ro
    networks:
      - app-network


  be:
    build:
      context: ./electro
      dockerfile: ./Dockerfile
    container_name: backend
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ElectroStore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123123
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: true
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-service
    ports:
      - "80:80"
    volumes:
      - ./fe:/usr/share/nginx/html:ro
    networks:
      - app-network
    depends_on:
      - be
      - db


networks:
  app-network:
    driver: bridge


volumes:
  mysqldata: